name: Build Flutter Project

on:
  push:
    tags:
      - 'v*'

jobs:

  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --split-per-abi
    - uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: build/app/outputs/apk/release/*.apk
        
  build_linux:
    name: Build Linux App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter build linux --release
    - run: |
        cd build/linux/x64/release/
        tar -czf dnd_dice_thingy_linux.tar.gz bundle
    - uses: actions/upload-artifact@v2
      with:
        name: linux-app
        path: build/linux/x64/release/dnd_dice_thingy_linux.tar.gz
        
  create_release:
    name: Create Release
    needs: [build_android, build_linux]
    runs-on: ubuntu-latest
    steps:
    - name: Download Android APKs
      uses: actions/download-artifact@v2
      with:
        name: android-apk
        path: android-apk
    - name: Download Linux App
      uses: actions/download-artifact@v2
      with:
        name: linux-app
        path: linux-app      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Android APKs
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: android-apk/app-armeabi-v7a-release.apk
        asset_name: app-armeabi-v7a-release.apk
        asset_content_type: application/vnd.android.package-archive
    - name: Upload app-arm64-v8a-release.apk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: android-apk/app-arm64-v8a-release.apk
        asset_name: app-arm64-v8a-release.apk
        asset_content_type: application/vnd.android.package-archive
    - name: Upload app-x86_64-release.apk
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: android-apk/app-x86_64-release.apk
        asset_name: app-x86_64-release.apk
        asset_content_type: application/vnd.android.package-archive
    - name: Upload Linux App Bundle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: linux-app/dnd_dice_thingy_linux.tar.gz
        asset_name: dnd_dice_thingy_linux.tar.gz
        asset_content_type: application/gzip
